### PR TITLE
:bug: Fix ResettableTimer to run as daemon=True

### PR DESCRIPTION
**Pull request by cp2004**
Should solve #214, there may be others and I will test it later. PR created against your development branch since I assume master is the latest release.

It doesn't want to automatically merge, but this shows you the problem. It might need a rebase against your development branch, but I can't do that now. Give it a couple of hours and I might have a chance.

I will also ask if this can be set as default in the class in OctoPrint, to avoid issues like this in the future.

### CODE REVIEW

**Comment by cp2004** [comment]
Issue reproduced, then confirmed fixed with this PR. Going to send one in to core OctoPrint as well to make this daemon by default, as you might be able to tell I have come across this issue before. Enjoy 😄 !

**Comment by StefanCohen** [comment]
Nice. Do you know why the call to the RepeatedTimer isn't affected?

**Comment by cp2004** [comment]
By default, RepeatedTimer is set to daemon=True in OctoPrint's source, whereas resettable is not. I'm typing out the PR to bring the two inline currently.

**Comment by StefanCohen** [comment]
Makes sense. Thanks!

**Pull request merged**
